export interface Service {
  id: string;
  name: string;
  category: string; // slug of category
  price: number;
  description: string;
  image: string;
  duration: string;
  rating: number;
}

export interface Category {
  id: number;
  name: string;
  description?: string | null;
  image: string;
  slug: string;
}

export interface Location {
  id: number;
  name: string;
  city: string;
  area?: string | null;
  image: string;
}

export interface Review {
  id: number;
  name: string;
  service: string;
  rating: number;
  comment: string;
  avatar?: string | null;
  date: string; // generated by DB
}

export interface Order {
  id: number;
  userId: string;
  serviceId: string; // stored as text; we stringify numeric IDs when saving
  status: 'pending' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled';
  customerName: string;
  phone: string;
  address: string;
  date: string;
  time: string;
  total: number;
  createdAt?: string; // DB returns created_at
}


