export interface Service {
  id: string;
  name: string;
  category: string; // slug of category
  price: number;
  discount: number;
  description: string;
  image: string;
  duration: string;
  rating: number;
}

export interface Category {
  id: string; // Changed from number to string to match database UUID
  name: string;
  description?: string | null;
  image: string;
  slug: string;
  icon?: string; // Added icon property for navbar display
}

export interface Location {
  id: string;
  name: string;
  city: string;
  area: string;
  image: string;
}

export interface Review {
  id: string; // Changed from number to string to match database UUID
  name: string;
  service: string;
  rating: number;
  comment: string;
  date: string; // generated by DB
  avatar?: string | null; // Made optional
}

export interface Order {
  id: string; // uuid in database
  userid: string;       // Corrected to lowercase userid
  serviceid: string;    // Corrected to lowercase serviceid
  status: 'pending' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled';
  customer_name: string; // Corrected to snake_case customer_name
  email: string;        // Customer email for notifications
  phone: string;
  address: string;
  date: string;
  time: string;
  total: number;
  created_at?: string; // DB returns created_at
}

export interface User {
  id: string; // uuid in database
  name: string;
  email: string;
  phone: string;
  message?: string; // Optional message from contact form
  source: 'contact_form' | 'order' | 'registration'; // How the user was added
  created_at?: string; // DB returns created_at
  updated_at?: string; // DB returns updated_at
}

export interface Blog {
  id: string; // uuid in database
  title: string;
  slug: string;
  content: string;
  hashtags: string;
  image: string;
  author: string;
  published: boolean;
  created_at?: string; // DB returns created_at
  updated_at?: string; // DB returns updated_at
}


