export interface Service {
  id: string;
  name: string;
  category: string; // slug of category
  price: number;
  description: string;
  image: string;
  duration: string;
  rating: number;
}

export interface Category {
  id: number;
  name: string;
  description?: string | null;
  image: string;
  slug: string;
}

export interface Location {
  id: string;
  name: string;
  city: string;
  area: string;
  image: string;
}

export interface Review {
  id: number;
  name: string;
  service: string;
  rating: number;
  comment: string;
  date: string; // generated by DB
  avatar?: string | null; // Made optional
}

export interface Order {
  id: string; // uuid in database
  userid: string;       // Corrected to lowercase userid
  serviceid: string;    // Corrected to lowercase serviceid
  status: 'pending' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled';
  customer_name: string; // Corrected to snake_case customer_name
  phone: string;
  address: string;
  date: string;
  time: string;
  total: number;
  created_at?: string; // DB returns created_at
}


